# Aliensevka custom build of Iosevka
[buildPlans.Aliensevka]
family = "Aliensevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Aliensevka.variants]
  inherits = "ss12"

    [buildPlans.Aliensevka.variants.design]
    capital-a = "round-top-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-q = "crossing"
    capital-w = "rounded-vertical-sides-serifless"
    a = "double-storey-toothless-corner"
    # g = "double-storey"
    w = "rounded-vertical-sides-flat-top-motion-serifed"
    x = "curly-serifless"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "high"
    brace = "curly"
    at = "fourfold-solid-inner"

  [buildPlans.Aliensevka.ligations]
  inherits = "clike"

[buildPlans.Aliensevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Aliensevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Aliensevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Aliensevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Aliensevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Aliensevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Aliensevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


