# Aliensevka custom build of Iosevka
[buildPlans.Aliensevka]
family = "Aliensevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Aliensevka.variants]
  inherits = "ss12"

    [buildPlans.Aliensevka.variants.design]
    capital-a = "round-top-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-q = "crossing"
    capital-w = "rounded-vertical-sides-serifless"
    a = "double-storey-toothless-corner"
    # g = "double-storey"
    w = "rounded-vertical-sides-flat-top-motion-serifed"
    x = "curly-serifless"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "high"
    brace = "curly"
    at = "fourfold-solid-inner"

  [buildPlans.Aliensevka.ligations]
  inherits = "clike"

[buildPlans.Aliensevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Aliensevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Aliensevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Aliensevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Aliensevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Aliensevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Aliensevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# Brainsevka custom build of Iosevka
[buildPlans.Brainsevka]
family = "Brainsevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Brainsevka.variants]
  inherits = "ss14"

  [buildPlans.Brainsevka.ligations]
  inherits = "clike"

[buildPlans.Brainsevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Brainsevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Brainsevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Brainsevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Brainsevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Brainsevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Brainsevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# Firasevka custom build of Iosevka
[buildPlans.Firasevka]
family = "Firasevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Firasevka.variants]
  inherits = "ss05"

  [buildPlans.Firasevka.ligations]
  inherits = "clike"

[buildPlans.Firasevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Firasevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Firasevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Firasevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Firasevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Firasevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Firasevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# Monasevka custom build of Iosevka
[buildPlans.Monasevka]
family = "Monasevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Monasevka.variants]
  inherits = "ss07"

  [buildPlans.Monasevka.ligations]
  inherits = "clike"

[buildPlans.Monasevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Monasevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Monasevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Monasevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Monasevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Monasevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Monasevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# Plexsevka custom build of Iosevka
[buildPlans.Plexsevka]
family = "Plexsevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Plexsevka.variants]
  inherits = "ss15"

  [buildPlans.Plexsevka.ligations]
  inherits = "clike"

[buildPlans.Plexsevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Plexsevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Plexsevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Plexsevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Plexsevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Plexsevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Plexsevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


# Ubunsevka custom build of Iosevka
[buildPlans.Ubunsevka]
family = "Ubunsevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Ubunsevka.variants]
  inherits = "ss12"

    [buildPlans.Ubunsevka.variants.design]
	underscore = "above-baseline"

  [buildPlans.Ubunsevka.ligations]
  inherits = "clike"

[buildPlans.Ubunsevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ubunsevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Ubunsevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Ubunsevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Ubunsevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Ubunsevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Ubunsevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


