# Ubunsevka custom build of Iosevka
[buildPlans.Ubunsevka]
family = "Ubunsevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Ubunsevka.variants]
  inherits = "ss12"

    [buildPlans.Ubunsevka.variants.design]
	underscore = "above-baseline"

  [buildPlans.Ubunsevka.ligations]
  inherits = "clike"

[buildPlans.Ubunsevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ubunsevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Ubunsevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Ubunsevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Ubunsevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Ubunsevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Ubunsevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"


